//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdRelationship.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/HouseHoldApp_Service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Household_Table", Namespace="http://schemas.datacontract.org/2004/07/HouseHoldApp_Service.Model")]
    [System.SerializableAttribute()]
    public partial class Household_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string applicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateofBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string middleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string suffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string applicationId {
            get {
                return this.applicationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.applicationIdField, value) != true)) {
                    this.applicationIdField = value;
                    this.RaisePropertyChanged("applicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateofBirth {
            get {
                return this.dateofBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.dateofBirthField, value) != true)) {
                    this.dateofBirthField = value;
                    this.RaisePropertyChanged("dateofBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.middleNameField, value) != true)) {
                    this.middleNameField = value;
                    this.RaisePropertyChanged("middleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                if ((object.ReferenceEquals(this.suffixField, value) != true)) {
                    this.suffixField = value;
                    this.RaisePropertyChanged("suffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relationship_Mapping", Namespace="http://schemas.datacontract.org/2004/07/HouseHoldApp_Service.Model")]
    [System.SerializableAttribute()]
    public partial class Relationship_Mapping : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parentUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int relationUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string relationshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int relationshipIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parentUserId {
            get {
                return this.parentUserIdField;
            }
            set {
                if ((this.parentUserIdField.Equals(value) != true)) {
                    this.parentUserIdField = value;
                    this.RaisePropertyChanged("parentUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int relationUserId {
            get {
                return this.relationUserIdField;
            }
            set {
                if ((this.relationUserIdField.Equals(value) != true)) {
                    this.relationUserIdField = value;
                    this.RaisePropertyChanged("relationUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string relationship {
            get {
                return this.relationshipField;
            }
            set {
                if ((object.ReferenceEquals(this.relationshipField, value) != true)) {
                    this.relationshipField = value;
                    this.RaisePropertyChanged("relationship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int relationshipId {
            get {
                return this.relationshipIdField;
            }
            set {
                if ((this.relationshipIdField.Equals(value) != true)) {
                    this.relationshipIdField = value;
                    this.RaisePropertyChanged("relationshipId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSearchInfo_table", Namespace="http://schemas.datacontract.org/2004/07/HouseHoldApp_Service.Model")]
    [System.SerializableAttribute()]
    public partial class UserSearchInfo_table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string applicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string applicationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateofBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string applicationId {
            get {
                return this.applicationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.applicationIdField, value) != true)) {
                    this.applicationIdField = value;
                    this.RaisePropertyChanged("applicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string applicationStatus {
            get {
                return this.applicationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.applicationStatusField, value) != true)) {
                    this.applicationStatusField = value;
                    this.RaisePropertyChanged("applicationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateofBirth {
            get {
                return this.dateofBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.dateofBirthField, value) != true)) {
                    this.dateofBirthField = value;
                    this.RaisePropertyChanged("dateofBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo_Table", Namespace="http://schemas.datacontract.org/2004/07/HouseHoldApp_Service.Model")]
    [System.SerializableAttribute()]
    public partial class UserInfo_Table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data_pdf", Namespace="http://schemas.datacontract.org/2004/07/HouseHoldApp_Service.Model")]
    [System.SerializableAttribute()]
    public partial class Data_pdf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string applicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateofBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string middleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parentUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int relationUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string relationshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string suffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string applicationId {
            get {
                return this.applicationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.applicationIdField, value) != true)) {
                    this.applicationIdField = value;
                    this.RaisePropertyChanged("applicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateofBirth {
            get {
                return this.dateofBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.dateofBirthField, value) != true)) {
                    this.dateofBirthField = value;
                    this.RaisePropertyChanged("dateofBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.middleNameField, value) != true)) {
                    this.middleNameField = value;
                    this.RaisePropertyChanged("middleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parentUserId {
            get {
                return this.parentUserIdField;
            }
            set {
                if ((this.parentUserIdField.Equals(value) != true)) {
                    this.parentUserIdField = value;
                    this.RaisePropertyChanged("parentUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int relationUserId {
            get {
                return this.relationUserIdField;
            }
            set {
                if ((this.relationUserIdField.Equals(value) != true)) {
                    this.relationUserIdField = value;
                    this.RaisePropertyChanged("relationUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string relationship {
            get {
                return this.relationshipField;
            }
            set {
                if ((object.ReferenceEquals(this.relationshipField, value) != true)) {
                    this.relationshipField = value;
                    this.RaisePropertyChanged("relationship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                if ((object.ReferenceEquals(this.suffixField, value) != true)) {
                    this.suffixField = value;
                    this.RaisePropertyChanged("suffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        HouseholdRelationship.ServiceReference1.CompositeType GetDataUsingDataContract(HouseholdRelationship.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<HouseholdRelationship.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(HouseholdRelationship.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddingUsersDetail", ReplyAction="http://tempuri.org/IService1/AddingUsersDetailResponse")]
        System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table> AddingUsersDetail(System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table> obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddingUsersDetail", ReplyAction="http://tempuri.org/IService1/AddingUsersDetailResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table>> AddingUsersDetailAsync(System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table> obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddingRelations", ReplyAction="http://tempuri.org/IService1/AddingRelationsResponse")]
        void AddingRelations(System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Relationship_Mapping> obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddingRelations", ReplyAction="http://tempuri.org/IService1/AddingRelationsResponse")]
        System.Threading.Tasks.Task AddingRelationsAsync(System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Relationship_Mapping> obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchingUsersDetail", ReplyAction="http://tempuri.org/IService1/SearchingUsersDetailResponse")]
        System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.UserSearchInfo_table> SearchingUsersDetail(HouseholdRelationship.ServiceReference1.UserSearchInfo_table obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchingUsersDetail", ReplyAction="http://tempuri.org/IService1/SearchingUsersDetailResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.UserSearchInfo_table>> SearchingUsersDetailAsync(HouseholdRelationship.ServiceReference1.UserSearchInfo_table obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditingRelationShipDetail", ReplyAction="http://tempuri.org/IService1/EditingRelationShipDetailResponse")]
        System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table> EditingRelationShipDetail(string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditingRelationShipDetail", ReplyAction="http://tempuri.org/IService1/EditingRelationShipDetailResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table>> EditingRelationShipDetailAsync(string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUpdatedUserDetails", ReplyAction="http://tempuri.org/IService1/DeleteUpdatedUserDetailsResponse")]
        void DeleteUpdatedUserDetails(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUpdatedUserDetails", ReplyAction="http://tempuri.org/IService1/DeleteUpdatedUserDetailsResponse")]
        System.Threading.Tasks.Task DeleteUpdatedUserDetailsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddingUser", ReplyAction="http://tempuri.org/IService1/AddingUserResponse")]
        bool AddingUser(HouseholdRelationship.ServiceReference1.UserInfo_Table tbl_UserDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddingUser", ReplyAction="http://tempuri.org/IService1/AddingUserResponse")]
        System.Threading.Tasks.Task<bool> AddingUserAsync(HouseholdRelationship.ServiceReference1.UserInfo_Table tbl_UserDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GettingRelationData", ReplyAction="http://tempuri.org/IService1/GettingRelationDataResponse")]
        System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Relationship_Mapping> GettingRelationData(string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GettingRelationData", ReplyAction="http://tempuri.org/IService1/GettingRelationDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Relationship_Mapping>> GettingRelationDataAsync(string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindExistingRelations", ReplyAction="http://tempuri.org/IService1/FindExistingRelationsResponse")]
        HouseholdRelationship.ServiceReference1.Relationship_Mapping FindExistingRelations(HouseholdRelationship.ServiceReference1.Relationship_Mapping tbl_RelationShip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindExistingRelations", ReplyAction="http://tempuri.org/IService1/FindExistingRelationsResponse")]
        System.Threading.Tasks.Task<HouseholdRelationship.ServiceReference1.Relationship_Mapping> FindExistingRelationsAsync(HouseholdRelationship.ServiceReference1.Relationship_Mapping tbl_RelationShip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateExistingUserRelations", ReplyAction="http://tempuri.org/IService1/UpdateExistingUserRelationsResponse")]
        void UpdateExistingUserRelations(HouseholdRelationship.ServiceReference1.Relationship_Mapping tbl_RelationShip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateExistingUserRelations", ReplyAction="http://tempuri.org/IService1/UpdateExistingUserRelationsResponse")]
        System.Threading.Tasks.Task UpdateExistingUserRelationsAsync(HouseholdRelationship.ServiceReference1.Relationship_Mapping tbl_RelationShip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ToGetPDFData", ReplyAction="http://tempuri.org/IService1/ToGetPDFDataResponse")]
        System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Data_pdf> ToGetPDFData(string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ToGetPDFData", ReplyAction="http://tempuri.org/IService1/ToGetPDFDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Data_pdf>> ToGetPDFDataAsync(string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Username", ReplyAction="http://tempuri.org/IService1/UsernameResponse")]
        string Username(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Username", ReplyAction="http://tempuri.org/IService1/UsernameResponse")]
        System.Threading.Tasks.Task<string> UsernameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HouseholdData", ReplyAction="http://tempuri.org/IService1/HouseholdDataResponse")]
        System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table> HouseholdData(string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HouseholdData", ReplyAction="http://tempuri.org/IService1/HouseholdDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table>> HouseholdDataAsync(string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserDetail", ReplyAction="http://tempuri.org/IService1/UserDetailResponse")]
        System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.UserInfo_Table> UserDetail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserDetail", ReplyAction="http://tempuri.org/IService1/UserDetailResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.UserInfo_Table>> UserDetailAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HouseholdRelationship.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HouseholdRelationship.ServiceReference1.IService1>, HouseholdRelationship.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public HouseholdRelationship.ServiceReference1.CompositeType GetDataUsingDataContract(HouseholdRelationship.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<HouseholdRelationship.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(HouseholdRelationship.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table> AddingUsersDetail(System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table> obj) {
            return base.Channel.AddingUsersDetail(obj);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table>> AddingUsersDetailAsync(System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table> obj) {
            return base.Channel.AddingUsersDetailAsync(obj);
        }
        
        public void AddingRelations(System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Relationship_Mapping> obj) {
            base.Channel.AddingRelations(obj);
        }
        
        public System.Threading.Tasks.Task AddingRelationsAsync(System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Relationship_Mapping> obj) {
            return base.Channel.AddingRelationsAsync(obj);
        }
        
        public System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.UserSearchInfo_table> SearchingUsersDetail(HouseholdRelationship.ServiceReference1.UserSearchInfo_table obj) {
            return base.Channel.SearchingUsersDetail(obj);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.UserSearchInfo_table>> SearchingUsersDetailAsync(HouseholdRelationship.ServiceReference1.UserSearchInfo_table obj) {
            return base.Channel.SearchingUsersDetailAsync(obj);
        }
        
        public System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table> EditingRelationShipDetail(string appId) {
            return base.Channel.EditingRelationShipDetail(appId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table>> EditingRelationShipDetailAsync(string appId) {
            return base.Channel.EditingRelationShipDetailAsync(appId);
        }
        
        public void DeleteUpdatedUserDetails(int id) {
            base.Channel.DeleteUpdatedUserDetails(id);
        }
        
        public System.Threading.Tasks.Task DeleteUpdatedUserDetailsAsync(int id) {
            return base.Channel.DeleteUpdatedUserDetailsAsync(id);
        }
        
        public bool AddingUser(HouseholdRelationship.ServiceReference1.UserInfo_Table tbl_UserDetails) {
            return base.Channel.AddingUser(tbl_UserDetails);
        }
        
        public System.Threading.Tasks.Task<bool> AddingUserAsync(HouseholdRelationship.ServiceReference1.UserInfo_Table tbl_UserDetails) {
            return base.Channel.AddingUserAsync(tbl_UserDetails);
        }
        
        public System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Relationship_Mapping> GettingRelationData(string appId) {
            return base.Channel.GettingRelationData(appId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Relationship_Mapping>> GettingRelationDataAsync(string appId) {
            return base.Channel.GettingRelationDataAsync(appId);
        }
        
        public HouseholdRelationship.ServiceReference1.Relationship_Mapping FindExistingRelations(HouseholdRelationship.ServiceReference1.Relationship_Mapping tbl_RelationShip) {
            return base.Channel.FindExistingRelations(tbl_RelationShip);
        }
        
        public System.Threading.Tasks.Task<HouseholdRelationship.ServiceReference1.Relationship_Mapping> FindExistingRelationsAsync(HouseholdRelationship.ServiceReference1.Relationship_Mapping tbl_RelationShip) {
            return base.Channel.FindExistingRelationsAsync(tbl_RelationShip);
        }
        
        public void UpdateExistingUserRelations(HouseholdRelationship.ServiceReference1.Relationship_Mapping tbl_RelationShip) {
            base.Channel.UpdateExistingUserRelations(tbl_RelationShip);
        }
        
        public System.Threading.Tasks.Task UpdateExistingUserRelationsAsync(HouseholdRelationship.ServiceReference1.Relationship_Mapping tbl_RelationShip) {
            return base.Channel.UpdateExistingUserRelationsAsync(tbl_RelationShip);
        }
        
        public System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Data_pdf> ToGetPDFData(string appId) {
            return base.Channel.ToGetPDFData(appId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Data_pdf>> ToGetPDFDataAsync(string appId) {
            return base.Channel.ToGetPDFDataAsync(appId);
        }
        
        public string Username(int id) {
            return base.Channel.Username(id);
        }
        
        public System.Threading.Tasks.Task<string> UsernameAsync(int id) {
            return base.Channel.UsernameAsync(id);
        }
        
        public System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table> HouseholdData(string appId) {
            return base.Channel.HouseholdData(appId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.Household_Table>> HouseholdDataAsync(string appId) {
            return base.Channel.HouseholdDataAsync(appId);
        }
        
        public System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.UserInfo_Table> UserDetail() {
            return base.Channel.UserDetail();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HouseholdRelationship.ServiceReference1.UserInfo_Table>> UserDetailAsync() {
            return base.Channel.UserDetailAsync();
        }
    }
}
